// entrypoints/options/options.vue
<template>
  <div class="max-w-3xl mx-auto p-4 space-y-4">
    <!-- Tabs -->
    <div role="tablist" class="tabs tabs-boxed">
      <a role="tab" :class="['tab', page_flag === 'ai' && 'tab-active']" @click="switchTab('ai')">
        AI 翻译
      </a>
      <a role="tab" :class="['tab', page_flag === 'collect' && 'tab-active']" @click="switchTab('collect')">
        收藏设置
      </a>
      <a role="tab" :class="['tab', page_flag === 'word' && 'tab-active']" @click="switchTab('word')">
        生词本
      </a>
    </div>

    <!-- AI Settings -->
    <div v-if="page_flag === 'ai'">
      <div class="card bg-base-100 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">AI 配置</h2>
          <div class="divider"></div>
          <div v-if="message" :class="['alert', messageType === 'success' ? 'alert-success' : 'alert-error']">
            <span>{{ message }}</span>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label class="label py-1">
                <span class="label-text">API 接口地址</span>
              </label>
              <input type="text" v-model="apiUrl" placeholder="https://api.example.com"
                class="input input-bordered w-full" />
            </div>

            <div>
              <label class="label">
                <span class="label-text py-1">SECRET KEY</span>
              </label>
              <input type="password" v-model="apiKey" placeholder="sk-xxxx" class="input w-full" />
            </div>

            <div>
              <label class="label">
                <span class="label-text py-1">AI 模型（翻译用）</span>
              </label>
              <input type="text" v-model="model" placeholder="gpt-4o" class="input w-full" />
            </div>
            
            <div>
              <label class="label">
                <span class="label-text py-1">AI 模型（查词用）</span>
              </label>
              <input type="text" v-model="word_model" placeholder="gpt-4o" class="input w-full" />
            </div>

            <div class="md:col-span-2">
              <label class="label">
                <span class="label-text py-1">Prompt</span>
              </label>
              <textarea v-model="prompt" class="textarea w-full min-h-28"
                placeholder="如果不想使用默认，请输入你想在 AI 翻译中使用的 Prompt"></textarea>
            </div>
          </div>

          <div class="card-actions justify-end mt-2 py-2">
            <button class="btn btn-secondary" :class="{ 'btn-disabled': testing }" @click="handleTest">
              <span v-if="testing" class="loading loading-spinner loading-sm"></span>
              <span>测试 API</span>
            </button>
            <button class="btn btn-primary" :class="{ 'btn-disabled': saving }" @click="handleSave">
              <span v-if="saving" class="loading loading-spinner loading-sm"></span>
              <span>保存设置</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Collect Settings -->
    <div v-else-if="page_flag === 'collect'">
      <div class="card bg-base-100 shadow-xl">
        <div class="card-body">
          <h2 class="card-title">收藏设置</h2>
          <div class="divider"></div>
          <div v-if="message" :class="['alert', messageType === 'success' ? 'alert-success' : 'alert-error']">
            <span>{{ message }}</span>
          </div>
          <div class="grid grid-cols-1 gap-4">
            <div class="flex items-center">
              <div class="px-2">
                生词收藏到欧路词典生词本
              </div>
              <div>
                <input type="checkbox" :checked="eudic_switch" @change="handleOpenEudicCollect" class="toggle" />
              </div>
            </div>
            <div v-if="eudic_switch" class="flex-1 ml-2">
              <div>
                <input type="text" v-model="eudic_token" placeholder="欧路词典授权信息（格式示例：NIS XXXXXXXXX）"
                  class="input input-bordered w-full" />
              </div>
              <div class="my-1">
                <a class="text-blue-300" href="https://my.eudic.net/OpenAPI/Authorization">获取欧路授权信息地址</a>
                我的个人主页>获取授权
              </div>
            </div>
          </div>

          <div class="card-actions justify-end mt-2 py-2">
            <button class="btn btn-primary" :class="{ 'btn-disabled': saving }" @click="handle_save_collection">
              <span v-if="saving" class="loading loading-spinner loading-sm"></span>
              <span>保存设置</span>
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Wordbook -->
    <div v-else-if="page_flag === 'word'">
      <div class="card bg-base-100 shadow-xl">
        <div class="card-body space-y-4">
          <div class="flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 class="card-title">收藏列表</h2>
              <p class="text-sm text-base-content/60">共 {{ wordCount }} 个单词</p>
            </div>
            <div class="flex items-center gap-2">
              <div class="badge" :class="eudic_switch ? 'badge-success' : 'badge-ghost'">
                {{ eudic_switch ? '远程同步已启用' : '远程同步未启用' }}
              </div>
              <button type="button" class="btn btn-outline btn-sm"
                :class="{ 'btn-disabled': !hasWords }" :disabled="!hasWords" @click="handleExportWords">
                导出单词
              </button>
              <button type="button" class="btn btn-primary btn-sm"
                :class="{ 'btn-disabled': syncing }" :disabled="syncing" @click="handleRemoteSync">
                <span v-if="syncing" class="loading loading-spinner loading-xs"></span>
                <span>同步所有单词</span>
              </button>
            </div>
          </div>
          <div v-if="message" :class="['alert', messageType === 'success' ? 'alert-success' : 'alert-error']">
            <span>{{ message }}</span>
          </div>
          <div class="divider my-0"></div>

          <div v-if="!hasWords" class="rounded-xl border border-dashed border-base-200 bg-base-200/40 p-6 text-center text-base-content/70">
            <p class="font-medium">暂未收藏单词</p>
            <p class="text-sm">在网页上选词并点击收藏后，将在此处展示。</p>
          </div>

          <div v-else class="space-y-2">
            <div
              v-for="(word_data, idx) in collection_words"
              :key="`${word_data.word}-${idx}`"
              class="grid grid-cols-1 gap-3 rounded-2xl border border-base-200 bg-base-200/30 px-4 py-3 transition hover:border-base-300 hover:bg-base-100 md:grid-cols-[auto_auto_1fr_auto] md:items-center"
            >
              <div class="text-base font-semibold text-base-content md:text-lg">{{ word_data.word }}</div>
              <div class="text-sm text-base-content/60 md:text-base">{{ formatPronunciation(word_data.pronunciation) }}</div>
              <div
                class="text-sm text-base-content/80 md:text-base md:truncate"
                :title="formatMeaning(word_data.meaning)"
              >
                {{ formatMeaning(word_data.meaning) }}
              </div>
              <div class="flex justify-start md:justify-end gap-2">
                <button
                  type="button"
                  class="btn btn-outline btn-sm"
                  :class="{ 'btn-disabled': isWordSyncing(idx) }"
                  :disabled="isWordSyncing(idx)"
                  @click="handleSyncSingleWord(word_data, idx)"
                >
                  <span v-if="isWordSyncing(idx)" class="loading loading-spinner loading-xs"></span>
                  <span v-else>单词同步</span>
                </button>
                <button
                  type="button"
                  class="btn btn-error btn-outline btn-sm"
                  @click="handleDeleteWord(idx)"
                >
                  删除
                </button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- 测试 API 结果弹窗 -->
    <dialog ref="testDialog" class="modal">
      <div class="modal-box max-w-2xl">
        <div class="flex items-center justify-between">
          <div class="flex items-center gap-2">
            <h3 class="font-bold text-lg">API 测试</h3>
            <span v-if="testing" class="loading loading-dots loading-sm"></span>
            <div class="badge" :class="isError ? 'badge-error' : 'badge-success'">
              {{ isError ? '错误' : (testing ? '测试中' : 'API可用！') }}
            </div>
          </div>
          <button class="btn btn-sm btn-circle btn-ghost" @click="closeTestDialog">✕</button>
        </div>

        <div class="mt-3">
          <div v-if="isError" class="alert alert-error">
            <span>{{ content }}</span>
          </div>
          <div v-else class="border rounded-2xl p-4 bg-gray-50">
            <div className="chat chat-start">
              <div className="chat-bubble chat-bubble-primary">{{ test_question }}</div>
            </div>
            <div className="chat chat-end">
              <div className="chat-bubble chat-bubble-info">{{ content }}</div>
            </div>
          </div>
        </div>
      </div>
      <form method="dialog" class="modal-backdrop">
        <button aria-label="close">close</button>
      </form>
    </dialog>
  </div>
</template>

<script lang="ts" setup>
import { ref, onMounted, computed } from 'vue'
import {
  ai_api_url_storage, ai_api_key_storage, ai_model_storage, ai_word_model_storage, ai_prompt_storage,
  youdao_token_storage, eudic_token_storage, eudic_switch_storage, collection_words_storage, options_tab_storage
} from '@/libs/local_storage'
import { WordData } from '@/libs/select_word'
import { collect_word } from '@/libs/word_collector'
import { OpenAI } from "openai";

type Tab = 'ai' | 'collect' | 'word'
const page_flag = ref<Tab>('ai')

const apiUrl = ref<string>('')
const apiKey = ref<string>('')
const model = ref<string>('')
const prompt = ref<string>('')
const word_model = ref<string>('')
const youdao_token = ref<string>('')
const eudic_token = ref<string>('')
const eudic_switch = ref<boolean>(false)
const collection_words = ref<WordData[]>([])
const wordCount = computed(() => collection_words.value?.length || 0)
const hasWords = computed(() => wordCount.value > 0)
const syncing = ref(false)
const wordSyncing = ref<Set<number>>(new Set())

const testing = ref(false)
const saving = ref(false)
const message = ref<string>('')
const messageType = ref<'success' | 'error'>('success')
let messageTimer: number | null = null


let content = ref<string>('')
const test_question = ref<string>('你好，我想测试一下你是否可用！')
const isError = ref(false)
const testDialog = ref<HTMLDialogElement | null>(null)

const openTestDialog = () => testDialog.value?.showModal()
const closeTestDialog = () => testDialog.value?.close()

onMounted(async () => {
  try {
    // 读取保存的tab状态，如果没读到则使用默认值 'ai'
    const savedTab = await options_tab_storage.getValue()
    page_flag.value = (savedTab as Tab) || 'ai'
    
    apiUrl.value = await ai_api_url_storage.getValue() || ''
    apiKey.value = await ai_api_key_storage.getValue() || ''
    model.value = await ai_model_storage.getValue() || ''
    word_model.value = await ai_word_model_storage.getValue() || ''
    prompt.value = await ai_prompt_storage.getValue() || ''
    youdao_token.value = await youdao_token_storage.getValue() || ''
    eudic_token.value = await eudic_token_storage.getValue() || ''
    eudic_switch.value = await eudic_switch_storage.getValue() || false
    collection_words.value = await collection_words_storage.getValue() || []
  } catch {
    console.warn('Failed to load saved settings')
  }
})

// 新增：切换tab并保存状态
const switchTab = async (tab: Tab) => {
  page_flag.value = tab
  try {
    await options_tab_storage.setValue(tab)
  } catch {
    console.warn('Failed to save tab state')
  }
}

const notify = (msg: string, type: 'success' | 'error' = 'success', duration = 2500) => {
  message.value = msg
  messageType.value = type
  if (messageTimer) {
    clearTimeout(messageTimer)
    messageTimer = null
  }
  if (duration > 0) {
    messageTimer = window.setTimeout(() => {
      message.value = ''
      messageTimer = null
    }, duration)
  }
}

const setWordSyncing = (idx: number, value: boolean) => {
  const next = new Set(wordSyncing.value)
  if (value) {
    next.add(idx)
  } else {
    next.delete(idx)
  }
  wordSyncing.value = next
}

const isWordSyncing = (idx: number) => wordSyncing.value.has(idx)

const formatPronunciation = (text: string | null | undefined) => {
  const output = text?.trim()
  return output && output !== '/' ? output : '—'
}

const formatMeaning = (text: string | null | undefined) => {
  if (!text) return '暂无释义'
  const stripped = text
    .replace(/<[^>]*>/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
  return stripped || '暂无释义'
}

const handleSave = async () => {
  try {
    saving.value = true
    if (!apiUrl.value?.trim() || !apiKey.value?.trim() || !model.value?.trim() || !word_model.value?.trim()) {
      notify('请填写 API 调用信息', 'error')
      return
    }
    await ai_api_url_storage.setValue(apiUrl.value.trim())
    await ai_api_key_storage.setValue(apiKey.value.trim())
    await ai_model_storage.setValue(model.value.trim())
    await ai_word_model_storage.setValue(word_model.value.trim() || null)
    await ai_prompt_storage.setValue(prompt.value.trim() || null)
    notify('已保存')
  } catch (e) {
    notify('保存失败', 'error')
  } finally {
    saving.value = false
  }
}

const handle_save_collection = async () => {
  try {
    saving.value = true
    if (eudic_switch.value && !eudic_token.value?.trim()) {
      notify('请填写欧路词典授权信息', 'error')
      return
    }
    await eudic_token_storage.setValue(eudic_token.value.trim() || null)
    await eudic_switch_storage.setValue(eudic_switch.value)
    notify('已保存')
  } catch (e) {
    notify('保存失败', 'error')
  } finally {
    saving.value = false
  }
}

const handleTest = async () => {
  if (!apiUrl.value?.trim() || !apiKey.value?.trim() || !model.value?.trim()) {
    isError.value = true
    content.value = 'API接口地址、AI模型、SecRetKey不能为空'
    openTestDialog()
    return
  }
  content.value = ''
  isError.value = false
  testing.value = true
  openTestDialog()

  try {
    const openai = new OpenAI({
      apiKey: apiKey.value.trim(),
      baseURL: apiUrl.value.trim(),
      dangerouslyAllowBrowser: true
    })

    const ai_stream = await openai.chat.completions.create({
      model: model.value.trim(),
      stream: true,
      messages: [
        { role: "user", content: test_question.value },
      ]
    })

    for await (const chunk of ai_stream) {
      const now_text = chunk?.choices?.[0]?.delta?.content ?? ''
      if (now_text) content.value += now_text
    }
  } catch (e: any) {
    isError.value = true
    content.value = e?.message || '请求失败'
  } finally {
    testing.value = false
  }
}

const handleRemoteSync = async () => {
  if (syncing.value) return

  if (!hasWords.value) {
    notify('暂无可同步的单词', 'error', 4000)
    return
  }

  if (!eudic_switch.value) {
    notify('请先在“收藏设置”中开启欧路词典同步', 'error', 4500)
    return
  }

  syncing.value = true
  try {
    let successCount = 0
    let failureCount = 0
    const failedWords: string[] = []
    const failureReasons: string[] = []

    for (const wordItem of collection_words.value) {
      const results = await collect_word(wordItem.word)
      const failedResults = results.filter(res => res.code !== 0)
      if (failedResults.length === 0) {
        successCount += 1
      } else {
        failureCount += 1
        failedWords.push(wordItem.word)
        failureReasons.push(...failedResults.map(res => res.message))
      }
    }

    if (failureCount === 0) {
      notify(`远程同步完成，成功同步 ${successCount} 个单词`, 'success', 4000)
    } else {
      const uniqueReasons = [...new Set(failureReasons.filter(Boolean))]
      const failedDetail = failedWords.length ? `：${failedWords.join('、')}` : ''
      const reasonDetail = uniqueReasons.length ? `（${uniqueReasons.join('；')}）` : ''
      notify(`远程同步完成，成功 ${successCount} 个，失败 ${failureCount} 个${failedDetail}${reasonDetail}`, 'error', 6000)
    }
  } catch (error: any) {
    console.error('Remote sync error', error)
    notify(error?.message ? `同步失败：${error.message}` : '同步失败，请稍后重试', 'error', 5000)
  } finally {
    syncing.value = false
  }
}

const handleSyncSingleWord = async (wordItem: WordData, idx: number) => {
  if (isWordSyncing(idx)) return

  if (!eudic_switch.value) {
    notify('请先在“收藏设置”中开启欧路词典同步', 'error', 4500)
    return
  }

  if (!eudic_token.value?.trim()) {
    notify('请在“收藏设置”中填写欧路词典授权信息', 'error', 4500)
    return
  }

  setWordSyncing(idx, true)
  try {
    const results = await collect_word(wordItem.word)
    const failedResults = results.filter(res => res.code !== 0)

    if (failedResults.length === 0) {
      notify(`已同步 ${wordItem.word}`, 'success', 3500)
    } else {
      const uniqueReasons = [...new Set(failedResults.map(res => res.message).filter(Boolean))]
      const reasonDetail = uniqueReasons.length ? `（${uniqueReasons.join('；')}）` : ''
      notify(`同步 ${wordItem.word} 失败${reasonDetail}`, 'error', 5000)
    }
  } catch (error: any) {
    console.error('Single word sync error', error)
    notify(error?.message ? `同步失败：${error.message}` : '同步失败，请稍后重试', 'error', 5000)
  } finally {
    setWordSyncing(idx, false)
  }
}

const handleDeleteWord = async (idx: number) => {
  if (idx < 0 || idx >= collection_words.value.length) return

  const wordToDelete = collection_words.value[idx].word

  try {
    const newCollectionWords = collection_words.value.filter((_, index) => index !== idx)
    collection_words.value = newCollectionWords
    await collection_words_storage.setValue(newCollectionWords)
    notify(`已删除 "${wordToDelete}"`, 'success', 2000)
  } catch (error) {
    console.error('Delete word error', error)
    notify('删除失败，请稍后重试', 'error', 3000)
  }
}

const handleExportWords = () => {
  if (!hasWords.value) {
    notify('暂无可导出的单词', 'error', 2000)
    return
  }

  try {
    const wordsText = collection_words.value
      .map(wordItem => wordItem.word.trim())
      .filter(word => word)
      .join('\n')

    const blob = new Blob([wordsText], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `words_${new Date().toISOString().split('T')[0]}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)

    notify(`已导出 ${wordCount.value} 个单词`, 'success', 2000)
  } catch (error) {
    console.error('Export words error', error)
    notify('导出失败，请稍后重试', 'error', 3000)
  }
}

const handleOpenEudicCollect = () => {
  eudic_switch.value = !eudic_switch.value
  eudic_switch_storage.setValue(eudic_switch.value)
}
</script>

<style scoped>
/* 可按需添加微调样式 */
</style>

// entrypoints/options/options.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { OpenAI } from "openai";

import {
  ai_api_key_storage,
  ai_api_url_storage,
  ai_model_storage,
  ai_prompt_storage,
  ai_word_model_storage,
  collection_words_storage,
  eudic_switch_storage,
  eudic_token_storage,
  options_tab_storage,
  DEFAULT_SENTENCE_HIGHLIGHT_COLOR,
  sentence_highlight_color_storage,
  youdao_token_storage,
} from "@/libs/local_storage";
import { SentenceHighlightStorage, type SentenceHighlightData } from "@/libs/sentence_highlight_storage";
import { type WordData } from "@/libs/select_word";
import { collect_word } from "@/libs/word_collector";
import { Badge } from "@/src/components/ui/badge";
import { Button } from "@/src/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/src/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/src/components/ui/dialog";
import { Input } from "@/src/components/ui/input";
import { ScrollArea } from "@/src/components/ui/scroll-area";
import { Switch } from "@/src/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/src/components/ui/tabs";
import { Textarea } from "@/src/components/ui/textarea";

type Tab = "ai" | "collect" | "word" | "sentence";

function formatDate(timestamp: number) {
  return new Date(timestamp).toLocaleString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
  });
}

function getWebsiteTitle(url: string) {
  try {
    const { hostname, pathname } = new URL(url);
    return hostname + (pathname !== "/" ? pathname : "");
  } catch {
    return url;
  }
}

function stripMeaning(text?: string | null) {
  if (!text) return "暂无释义";
  return text.replace(/<[^>]*>/g, " ").replace(/\s+/g, " ").trim() || "暂无释义";
}

export default function OptionsPage() {
  const [tab, setTab] = useState<Tab>("ai");
  const [apiUrl, setApiUrl] = useState("");
  const [apiKey, setApiKey] = useState("");
  const [model, setModel] = useState("");
  const [wordModel, setWordModel] = useState("");
  const [prompt, setPrompt] = useState("");
  const [youdaoToken, setYoudaoToken] = useState("");
  const [eudicToken, setEudicToken] = useState("");
  const [eudicSwitch, setEudicSwitch] = useState(false);
  const [collectionWords, setCollectionWords] = useState<WordData[]>([]);
  const [sentenceHighlights, setSentenceHighlights] = useState<SentenceHighlightData[]>([]);
  const [selectedWebsite, setSelectedWebsite] = useState("");
  const [websiteSearchQuery, setWebsiteSearchQuery] = useState("");
  const [sentenceHighlightColor, setSentenceHighlightColor] = useState(DEFAULT_SENTENCE_HIGHLIGHT_COLOR);
  const [saving, setSaving] = useState(false);
  const [testing, setTesting] = useState(false);
  const [syncing, setSyncing] = useState(false);
  const [wordSyncing, setWordSyncing] = useState<number[]>([]);
  const [message, setMessage] = useState<{ text: string; type: "success" | "error" } | null>(null);
  const [dialogOpen, setDialogOpen] = useState(false);
  const [dialogContent, setDialogContent] = useState("");
  const [dialogError, setDialogError] = useState(false);
  const messageTimerRef = useRef<number | null>(null);

  useEffect(() => {
    let active = true;
    (async () => {
      const [
        savedTab,
        storedApiUrl,
        storedApiKey,
        storedModel,
        storedWordModel,
        storedPrompt,
        storedYoudaoToken,
        storedEudicToken,
        storedEudicSwitch,
        storedWords,
        storedColor,
      ] = await Promise.all([
        options_tab_storage.getValue(),
        ai_api_url_storage.getValue(),
        ai_api_key_storage.getValue(),
        ai_model_storage.getValue(),
        ai_word_model_storage.getValue(),
        ai_prompt_storage.getValue(),
        youdao_token_storage.getValue(),
        eudic_token_storage.getValue(),
        eudic_switch_storage.getValue(),
        collection_words_storage.getValue(),
        sentence_highlight_color_storage.getValue(),
      ]);
      const highlights = await SentenceHighlightStorage.getAllHighlights();
      if (!active) return;
      setTab((savedTab as Tab) || "ai");
      setApiUrl(storedApiUrl || "");
      setApiKey(storedApiKey || "");
      setModel(storedModel || "");
      setWordModel(storedWordModel || "");
      setPrompt(storedPrompt || "");
      setYoudaoToken(storedYoudaoToken || "");
      setEudicToken(storedEudicToken || "");
      setEudicSwitch(Boolean(storedEudicSwitch));
      setCollectionWords(storedWords || []);
      setSentenceHighlightColor(storedColor || DEFAULT_SENTENCE_HIGHLIGHT_COLOR);
      setSentenceHighlights(highlights);
    })().catch(() => undefined);
    return () => {
      active = false;
    };
  }, []);

  useEffect(() => {
    options_tab_storage.setValue(tab);
  }, [tab]);

  function notify(text: string, type: "success" | "error" = "success") {
    setMessage({ text, type });
    if (messageTimerRef.current) {
      window.clearTimeout(messageTimerRef.current);
    }
    messageTimerRef.current = window.setTimeout(() => setMessage(null), 3000);
  }

  async function refreshHighlights() {
    const highlights = await SentenceHighlightStorage.getAllHighlights();
    setSentenceHighlights(highlights);
    if (selectedWebsite && !highlights.some((item) => item.url === selectedWebsite)) {
      setSelectedWebsite("");
    }
  }

  const websiteGroups = useMemo(() => {
    const groups = new Map<string, { title: string; url: string; highlights: SentenceHighlightData[] }>();
    sentenceHighlights.forEach((highlight) => {
      if (!groups.has(highlight.url)) {
        groups.set(highlight.url, {
          title: highlight.title || getWebsiteTitle(highlight.url),
          url: highlight.url,
          highlights: [],
        });
      }
      groups.get(highlight.url)!.highlights.push(highlight);
    });
    return [...groups.values()].sort((a, b) => {
      const aLatest = Math.max(...a.highlights.map((item) => item.timestamp));
      const bLatest = Math.max(...b.highlights.map((item) => item.timestamp));
      return bLatest - aLatest;
    });
  }, [sentenceHighlights]);

  const filteredWebsiteGroups = useMemo(() => {
    const query = websiteSearchQuery.trim().toLowerCase();
    if (!query) return websiteGroups;
    return websiteGroups.filter(
      (group) =>
        group.title.toLowerCase().includes(query) || group.url.toLowerCase().includes(query),
    );
  }, [websiteGroups, websiteSearchQuery]);

  const selectedWebsiteHighlights = useMemo(() => {
    return websiteGroups
      .find((group) => group.url === selectedWebsite)
      ?.highlights.slice()
      .sort((a, b) => b.timestamp - a.timestamp) || [];
  }, [selectedWebsite, websiteGroups]);

  async function handleSaveAi() {
    if (!apiUrl.trim() || !apiKey.trim() || !model.trim() || !wordModel.trim()) {
      notify("请填写 API 调用信息", "error");
      return;
    }
    setSaving(true);
    try {
      await Promise.all([
        ai_api_url_storage.setValue(apiUrl.trim()),
        ai_api_key_storage.setValue(apiKey.trim()),
        ai_model_storage.setValue(model.trim()),
        ai_word_model_storage.setValue(wordModel.trim()),
        ai_prompt_storage.setValue(prompt.trim() || null),
      ]);
      notify("AI 配置已保存");
    } catch {
      notify("保存失败", "error");
    } finally {
      setSaving(false);
    }
  }

  async function handleSaveCollection() {
    if (eudicSwitch && !eudicToken.trim()) {
      notify("请填写欧路词典授权信息", "error");
      return;
    }
    setSaving(true);
    try {
      await Promise.all([
        eudic_token_storage.setValue(eudicToken.trim() || null),
        eudic_switch_storage.setValue(eudicSwitch),
        youdao_token_storage.setValue(youdaoToken.trim() || null),
      ]);
      notify("收藏设置已保存");
    } catch {
      notify("保存失败", "error");
    } finally {
      setSaving(false);
    }
  }

  async function handleTest() {
    if (!apiUrl.trim() || !apiKey.trim() || !model.trim()) {
      setDialogError(true);
      setDialogContent("API 接口地址、模型、Secret Key 不能为空");
      setDialogOpen(true);
      return;
    }

    setDialogOpen(true);
    setDialogContent("");
    setDialogError(false);
    setTesting(true);
    try {
      const openai = new OpenAI({
        apiKey: apiKey.trim(),
        baseURL: apiUrl.trim(),
        dangerouslyAllowBrowser: true,
      });
      const stream = await openai.chat.completions.create({
        model: model.trim(),
        stream: true,
        messages: [{ role: "user", content: "你好，我想测试一下你是否可用！" }],
      });
      for await (const chunk of stream) {
        const nowText = chunk?.choices?.[0]?.delta?.content ?? "";
        if (nowText) {
          setDialogContent((value) => value + nowText);
        }
      }
    } catch (error: any) {
      setDialogError(true);
      setDialogContent(error?.message || "请求失败");
    } finally {
      setTesting(false);
    }
  }

  async function handleRemoteSync() {
    if (!collectionWords.length) {
      notify("暂无可同步的单词", "error");
      return;
    }
    if (!eudicSwitch) {
      notify("请先开启欧路词典同步", "error");
      return;
    }

    setSyncing(true);
    try {
      let successCount = 0;
      let failureCount = 0;
      const failedWords: string[] = [];
      for (const word of collectionWords) {
        const results = await collect_word(word.word);
        const failed = results.filter((item) => item.code !== 0);
        if (failed.length) {
          failureCount += 1;
          failedWords.push(word.word);
        } else {
          successCount += 1;
        }
      }
      if (!failureCount) {
        notify(`远程同步完成，成功 ${successCount} 个单词`);
      } else {
        notify(`远程同步完成，成功 ${successCount} 个，失败 ${failureCount} 个：${failedWords.join("、")}`, "error");
      }
    } catch (error: any) {
      notify(error?.message ? `同步失败：${error.message}` : "同步失败", "error");
    } finally {
      setSyncing(false);
    }
  }

  async function handleSyncSingleWord(word: WordData, idx: number) {
    if (!eudicSwitch) {
      notify("请先开启欧路词典同步", "error");
      return;
    }
    setWordSyncing((list) => [...list, idx]);
    try {
      const results = await collect_word(word.word);
      const failed = results.filter((item) => item.code !== 0);
      notify(failed.length ? `同步 ${word.word} 失败` : `已同步 ${word.word}`, failed.length ? "error" : "success");
    } finally {
      setWordSyncing((list) => list.filter((item) => item !== idx));
    }
  }

  async function handleDeleteWord(idx: number) {
    const next = collectionWords.filter((_, index) => index !== idx);
    setCollectionWords(next);
    await collection_words_storage.setValue(next);
    notify("已删除单词");
  }

  function handleExportWords() {
    if (!collectionWords.length) {
      notify("暂无可导出的单词", "error");
      return;
    }
    const wordsText = collectionWords.map((item) => item.word.trim()).filter(Boolean).join("\n");
    const blob = new Blob([wordsText], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `words_${new Date().toISOString().split("T")[0]}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    notify(`已导出 ${collectionWords.length} 个单词`);
  }

  async function handleSentenceHighlightColorChange(color: string) {
    setSentenceHighlightColor(color);
    await sentence_highlight_color_storage.setValue(color);
    notify("高亮颜色已保存");
  }

  async function handleResetSentenceHighlightColor() {
    setSentenceHighlightColor(DEFAULT_SENTENCE_HIGHLIGHT_COLOR);
    await sentence_highlight_color_storage.setValue(DEFAULT_SENTENCE_HIGHLIGHT_COLOR);
    notify("已恢复默认高亮颜色");
  }

  async function handleDeleteHighlight(id: string) {
    await SentenceHighlightStorage.removeHighlight(id);
    await refreshHighlights();
    notify("已删除高亮");
  }

  async function handleClearWebsiteHighlights() {
    if (!selectedWebsite || !window.confirm(`确定要清空 "${getWebsiteTitle(selectedWebsite)}" 的所有高亮吗？`)) {
      return;
    }
    await SentenceHighlightStorage.clearHighlights(selectedWebsite);
    await refreshHighlights();
    notify("已清空网站高亮");
  }

  async function handleClearAllHighlights() {
    if (!window.confirm("确定要清空所有句子高亮吗？此操作不可恢复。")) {
      return;
    }
    for (const highlight of sentenceHighlights) {
      await SentenceHighlightStorage.removeHighlight(highlight.id);
    }
    await refreshHighlights();
    notify("已清空所有高亮");
  }

  async function copyToClipboard(text: string) {
    try {
      await navigator.clipboard.writeText(text);
      notify("已复制到剪贴板");
    } catch {
      notify("复制失败", "error");
    }
  }

  function handleExportHighlights() {
    if (!sentenceHighlights.length) {
      notify("暂无可导出的高亮", "error");
      return;
    }
    const headers = ["网站", "句子", "时间", "颜色", "备注"];
    const csvContent = [
      headers.join(","),
      ...sentenceHighlights
        .slice()
        .sort((a, b) => b.timestamp - a.timestamp)
        .map((highlight) =>
          [
            getWebsiteTitle(highlight.url),
            highlight.sentence,
            formatDate(highlight.timestamp),
            highlight.color || DEFAULT_SENTENCE_HIGHLIGHT_COLOR,
            highlight.note || "",
          ]
            .map((item) => `"${String(item).replace(/"/g, '""')}"`)
            .join(","),
        ),
    ].join("\n");

    const blob = new Blob(["\uFEFF" + csvContent], { type: "text/csv;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `sentence_highlights_${new Date().toISOString().split("T")[0]}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    notify(`已导出 ${sentenceHighlights.length} 个高亮`);
  }

  return (
    <main className="min-h-screen px-4 py-6 text-slate-900">
      <div className="mx-auto max-w-6xl space-y-4">

        {message ? (
          <div
            className={`rounded-2xl border px-4 py-3 text-sm ${
              message.type === "success"
                ? "border-emerald-200 bg-emerald-50 text-emerald-700"
                : "border-red-200 bg-red-50 text-red-700"
            }`}
          >
            {message.text}
          </div>
        ) : null}

        <Tabs value={tab} onValueChange={(value) => setTab(value as Tab)} className="space-y-4">
          <TabsList className="w-full flex-wrap gap-1">
            <TabsTrigger value="ai">AI 翻译</TabsTrigger>
            <TabsTrigger value="collect">收藏设置</TabsTrigger>
            <TabsTrigger value="word">生词本</TabsTrigger>
            <TabsTrigger value="sentence">句子高亮</TabsTrigger>
          </TabsList>

          <TabsContent value="ai">
            <Card>
              <CardHeader>
                <CardTitle>AI 配置</CardTitle>
              </CardHeader>
              <CardContent className="grid gap-4 md:grid-cols-2">
                <div className="space-y-2">
                  <label className="text-sm font-medium">API 接口地址</label>
                  <Input value={apiUrl} onChange={(e) => setApiUrl(e.target.value)} placeholder="https://api.example.com" />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">Secret Key</label>
                  <Input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder="sk-xxxx" />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">AI 模型（翻译）</label>
                  <Input value={model} onChange={(e) => setModel(e.target.value)} placeholder="gpt-4o" />
                </div>
                <div className="space-y-2">
                  <label className="text-sm font-medium">AI 模型（查词）</label>
                  <Input value={wordModel} onChange={(e) => setWordModel(e.target.value)} placeholder="gpt-4o-mini" />
                </div>
                <div className="space-y-2 md:col-span-2">
                  <label className="text-sm font-medium">Prompt</label>
                  <Textarea value={prompt} onChange={(e) => setPrompt(e.target.value)} placeholder="如果不想使用默认，请输入自定义 Prompt" />
                </div>
                <div className="md:col-span-2 flex justify-end gap-3">
                  <Button variant="secondary" onClick={handleTest} disabled={testing}>
                    {testing ? "测试中..." : "测试 API"}
                  </Button>
                  <Button onClick={handleSaveAi} disabled={saving}>
                    {saving ? "保存中..." : "保存设置"}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="collect">
            <Card>
              <CardHeader>
                <CardTitle>收藏设置</CardTitle>
              </CardHeader>
              <CardContent className="space-y-5">
                <div className="flex items-center justify-between rounded-2xl border border-slate-200 bg-slate-50/80 p-4">
                  <div>
                    <div className="text-sm">生词同步到欧路词典</div>
                    <p className="font-medium text-slate-500">开启后可在生词本中执行单词同步和批量远程同步。</p>
                  </div>
                  <Switch checked={eudicSwitch} onCheckedChange={setEudicSwitch} />
                </div>
                {eudicSwitch ? (
                  <div className="grid gap-4 md:grid-cols-2">
                    <div className="space-y-2 md:col-span-2">
                      <label className="text-sm font-medium">欧路词典授权信息</label>
                      <Input value={eudicToken} onChange={(e) => setEudicToken(e.target.value)} placeholder="NIS XXXXXXXXX" />
                    </div>
                  </div>
                ) : null}
                <div className="flex justify-end gap-3">
                  <Button variant="outline" onClick={handleRemoteSync} disabled={syncing || !collectionWords.length}>
                    {syncing ? "同步中..." : "远程同步"}
                  </Button>
                  <Button onClick={handleSaveCollection} disabled={saving}>
                    {saving ? "保存中..." : "保存设置"}
                  </Button>
                </div>
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="word">
            <Card>
              <CardHeader>
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <CardTitle>生词本</CardTitle>
                    <CardDescription>共 {collectionWords.length} 个单词，可删除、单词同步和导出。</CardDescription>
                  </div>
                  <div className="flex gap-2">
                    <Button variant="outline" onClick={handleRemoteSync} disabled={syncing || !collectionWords.length}>
                      {syncing ? "同步中..." : "批量同步"}
                    </Button>
                    <Button onClick={handleExportWords} disabled={!collectionWords.length}>
                      导出 TXT
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {!collectionWords.length ? (
                  <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/60 p-8 text-center text-sm text-slate-500">
                    暂无单词收藏。你可以在网页上选中单词后打开单词卡进行收藏。
                  </div>
                ) : (
                  <ScrollArea className="max-h-[34rem] space-y-3 pr-2">
                    <div className="space-y-3">
                      {collectionWords.map((word, idx) => (
                        <div key={`${word.word}-${idx}`} className="rounded-2xl border border-slate-200 bg-white p-4">
                          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
                            <div className="space-y-1">
                              <div className="text-lg font-semibold">{word.word}</div>
                              <div className="text-sm text-slate-500">{word.pronunciation?.trim() || "—"}</div>
                              <div className="max-w-3xl text-sm leading-6 text-slate-600">{stripMeaning(word.meaning)}</div>
                            </div>
                            <div className="flex gap-2">
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => handleSyncSingleWord(word, idx)}
                                disabled={wordSyncing.includes(idx)}
                              >
                                {wordSyncing.includes(idx) ? "同步中..." : "单词同步"}
                              </Button>
                              <Button variant="destructive" size="sm" onClick={() => handleDeleteWord(idx)}>
                                删除
                              </Button>
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                  </ScrollArea>
                )}
              </CardContent>
            </Card>
          </TabsContent>

          <TabsContent value="sentence">
            <Card>
              <CardHeader>
                <div className="flex flex-wrap items-center justify-between gap-4">
                  <div>
                    <CardTitle>句子高亮</CardTitle>
                    <CardDescription>共 {sentenceHighlights.length} 个高亮，覆盖 {websiteGroups.length} 个网站。</CardDescription>
                  </div>
                  <div className="flex items-center gap-3">
                    <label className="flex items-center gap-2 text-sm text-slate-500">
                      <span>高亮颜色</span>
                      <input
                        type="color"
                        value={sentenceHighlightColor}
                        onChange={(e) => handleSentenceHighlightColorChange(e.target.value)}
                        className="h-9 w-9 rounded-lg border border-slate-200 bg-transparent"
                      />
                    </label>
                    <Button variant="outline" size="sm" onClick={handleResetSentenceHighlightColor}>
                      恢复默认颜色
                    </Button>
                    <Button variant="outline" size="sm" onClick={handleExportHighlights} disabled={!sentenceHighlights.length}>
                      导出
                    </Button>
                    <Button variant="destructive" size="sm" onClick={handleClearAllHighlights} disabled={!sentenceHighlights.length}>
                      清空
                    </Button>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {!sentenceHighlights.length ? (
                  <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/60 p-8 text-center text-sm text-slate-500">
                    暂无句子高亮。在网页选中句子并执行高亮后，这里会自动汇总。
                  </div>
                ) : (
                  <div className="grid gap-4 lg:grid-cols-[320px_minmax(0,1fr)]">
                    <div className="space-y-3">
                      <Input
                        value={websiteSearchQuery}
                        onChange={(e) => setWebsiteSearchQuery(e.target.value)}
                        placeholder="搜索网站..."
                      />
                      <ScrollArea className="max-h-[34rem] space-y-2 pr-2">
                        <div className="space-y-2">
                          {filteredWebsiteGroups.map((group) => (
                            <button
                              key={group.url}
                              type="button"
                              onClick={() => setSelectedWebsite(group.url)}
                              className={`w-full rounded-2xl border p-4 text-left transition ${
                                selectedWebsite === group.url
                                  ? "border-sky-300 bg-sky-50"
                                  : "border-slate-200 bg-white hover:border-slate-300"
                              }`}
                            >
                              <div className="font-medium">{group.title}</div>
                              <div className="mt-1 text-xs text-slate-500">{group.url}</div>
                              <div className="mt-2 text-xs text-slate-400">{group.highlights.length} 个高亮</div>
                            </button>
                          ))}
                        </div>
                      </ScrollArea>
                    </div>
                    <div>
                      {!selectedWebsite ? (
                        <div className="rounded-2xl border border-dashed border-slate-200 bg-slate-50/60 p-8 text-center text-sm text-slate-500">
                          请选择左侧网站查看高亮详情。
                        </div>
                      ) : (
                        <div className="space-y-3">
                          <div className="flex flex-wrap items-center justify-between gap-3">
                            <div>
                              <h3 className="text-lg font-semibold">{getWebsiteTitle(selectedWebsite)}</h3>
                              <p className="text-sm text-slate-500">{selectedWebsite}</p>
                            </div>
                            <div className="flex gap-2">
                              <Button variant="outline" size="sm" onClick={() => window.open(selectedWebsite, "_blank")}>
                                打开网页
                              </Button>
                              <Button variant="destructive" size="sm" onClick={handleClearWebsiteHighlights}>
                                清空网站高亮
                              </Button>
                            </div>
                          </div>
                          <ScrollArea className="max-h-[34rem] space-y-3 pr-2">
                            <div className="space-y-3">
                              {selectedWebsiteHighlights.map((highlight) => (
                                <div key={highlight.id} className="rounded-2xl border border-slate-200 bg-white p-4">
                                  <div className="flex flex-col gap-3 md:flex-row md:items-start md:justify-between">
                                    <div className="space-y-2">
                                      <p className="text-sm leading-6 text-slate-700">{highlight.sentence}</p>
                                      <div className="flex flex-wrap items-center gap-2 text-xs text-slate-400">
                                        <span>{formatDate(highlight.timestamp)}</span>
                                        <span>{highlight.color || DEFAULT_SENTENCE_HIGHLIGHT_COLOR}</span>
                                        {highlight.note ? <span>{highlight.note}</span> : null}
                                      </div>
                                    </div>
                                    <div className="flex gap-2">
                                      <Button variant="outline" size="sm" onClick={() => copyToClipboard(highlight.sentence)}>
                                        复制
                                      </Button>
                                      <Button variant="destructive" size="sm" onClick={() => handleDeleteHighlight(highlight.id)}>
                                        删除
                                      </Button>
                                    </div>
                                  </div>
                                </div>
                              ))}
                            </div>
                          </ScrollArea>
                        </div>
                      )}
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>
          </TabsContent>
        </Tabs>
      </div>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <div className="flex items-center justify-between gap-3">
              <div>
                <DialogTitle>API 测试</DialogTitle>
                <DialogDescription>直接使用当前配置调用翻译模型，展示流式返回结果。</DialogDescription>
              </div>
              <Badge variant={dialogError ? "error" : testing ? "secondary" : "success"}>
                {dialogError ? "错误" : testing ? "测试中" : "可用"}
              </Badge>
            </div>
          </DialogHeader>
          <div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50/80 p-4 text-sm leading-7 text-slate-700">
            {dialogContent || "等待响应..."}
          </div>
          <div className="mt-4 flex justify-end">
            <Button variant="outline" onClick={() => setDialogOpen(false)}>
              关闭
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </main>
  );
}
