// entrypoints/content/views/word_card.tsx
import { useEffect, useRef, useState } from "react";
import { OpenAI } from "openai";

import type { EventManager } from "@/libs/event_manager";
import {
  ai_api_key_storage,
  ai_api_url_storage,
  ai_prompt_storage,
  ai_word_model_storage,
  collection_words_storage,
} from "@/libs/local_storage";
import type { SelectInfo, WordData } from "@/libs/select_word";
import { collect_word } from "@/libs/word_collector";

type SelectedWordStore = {
  getValue: () => Promise<SelectInfo | null>;
};

type WordCardProps = {
  eventManager: EventManager;
  selectedWordStore: SelectedWordStore;
  cachedWordData?: WordData | null;
};

const defaultPrompt = `
You are an assistant that extracts dictionary-like information.

I will give you a word and its context.  
Return the result strictly as a JSON object with the following TypeScript type:

export type WordData = {
    word: string;
    pronunciation: string;
    meaning: string;
};

Rules:
- Do not include anything outside the JSON.
- "word": exactly the given word.
- "pronunciation": return the phonetic transcription in IPA if possible (e.g., "/wɜːd/"), otherwise leave it as an empty string.
- "meaning": give the chinese meaning of the word in the provided context, concise but clear.just the word meaning, don't include context, this is important.
`;

export default function WordCard({
  eventManager,
  selectedWordStore,
  cachedWordData = null,
}: WordCardProps) {
  const [loading, setLoading] = useState(true);
  const [wordData, setWordData] = useState<WordData | null>(cachedWordData);
  const [isCollected, setIsCollected] = useState(false);
  const audioRef = useRef<HTMLAudioElement | null>(null);

  useEffect(() => {
    let active = true;

    async function load() {
      if (cachedWordData) {
        setWordData(cachedWordData);
        const storedWords = (await collection_words_storage.getValue()) || [];
        if (active) {
          setIsCollected(storedWords.some((item) => item.word === cachedWordData.word));
          setLoading(false);
        }
        return;
      }

      const [apiKey, apiUrl, model, customPrompt, selected] = await Promise.all([
        ai_api_key_storage.getValue(),
        ai_api_url_storage.getValue(),
        ai_word_model_storage.getValue(),
        ai_prompt_storage.getValue(),
        selectedWordStore.getValue(),
      ]);

      if (!selected?.word) {
        if (active) {
          setWordData({ word: "Error", pronunciation: "", meaning: "未找到当前选中的单词。" });
          setLoading(false);
        }
        return;
      }

      if (!apiKey || !apiUrl || !model) {
        if (active) {
          setWordData({
            word: "Error",
            pronunciation: "",
            meaning: "Please set your OpenAI API configuration in the settings.",
          });
          setLoading(false);
        }
        return;
      }

      try {
        const openai = new OpenAI({
          apiKey,
          baseURL: apiUrl,
          dangerouslyAllowBrowser: true,
        });
        const response = await openai.chat.completions.create({
          model,
          messages: [
            { role: "system", content: customPrompt || defaultPrompt },
            { role: "user", content: `Word: ${selected.word} Context: ${selected.context}` },
          ],
          response_format: { type: "json_object" },
        });
        const content = response.choices[0]?.message?.content;
        const parsed = JSON.parse(content || "{}") as WordData;
        const storedWords = (await collection_words_storage.getValue()) || [];

        if (active) {
          setWordData(parsed);
          setIsCollected(storedWords.some((item) => item.word === parsed.word));
        }
      } catch (error) {
        if (active) {
          console.error("Word lookup error:", error);
          setWordData({
            word: selected.word,
            pronunciation: "",
            meaning: "请求查词接口失败，请检查配置和网络。",
          });
        }
      } finally {
        if (active) {
          setLoading(false);
        }
      }
    }

    load();

    return () => {
      active = false;
      audioRef.current?.pause();
      audioRef.current = null;
    };
  }, [cachedWordData, selectedWordStore]);

  async function handleCollect() {
    if (!wordData || isCollected) return;
    const storedWords = (await collection_words_storage.getValue()) || [];
    await collection_words_storage.setValue([...storedWords, wordData]);
    const selected = await selectedWordStore.getValue();
    await collect_word(wordData.word, selected?.context);
    setIsCollected(true);
  }

  function handleHighlight() {
    if (!wordData?.word) return;
    eventManager.emit("highlight-word", {
      word: wordData.word,
      wordData,
    });
    eventManager.emit("close-word-card");
  }

  function playAudio() {
    if (!wordData?.word) return;

    const fallbackToRemoteAudio = () => {
      const audio = new Audio(
        `https://dict.youdao.com/dictvoice?audio=${encodeURIComponent(wordData.word)}&type=2`,
      );
      audioRef.current = audio;
      audio.play().catch((error) => {
        console.error("Audio playback failed:", error);
      });
    };

    const synth = window.speechSynthesis;
    if (!synth || typeof SpeechSynthesisUtterance === "undefined") {
      fallbackToRemoteAudio();
      return;
    }

    try {
      synth.cancel();
      const utterance = new SpeechSynthesisUtterance(wordData.word);
      utterance.lang = "en-US";
      utterance.rate = 0.95;
      utterance.pitch = 1;

      const voices = synth.getVoices();
      const englishVoice = voices.find(
        (voice) => voice.lang.toLowerCase().startsWith("en") && !voice.localService,
      ) || voices.find((voice) => voice.lang.toLowerCase().startsWith("en"));
      if (englishVoice) {
        utterance.voice = englishVoice;
      }

      utterance.onerror = () => {
        fallbackToRemoteAudio();
      };

      synth.speak(utterance);
    } catch (error) {
      console.error("Speech synthesis failed:", error);
      fallbackToRemoteAudio();
    }
  }

  return (
    <div className="min-w-[360px] max-w-[480px] rounded-[10px] border border-slate-200 bg-white p-4 text-slate-900 shadow-[0_20px_45px_rgba(15,23,42,0.12)]">
      {loading ? (
        <div className="space-y-3">
          <div className="h-7 w-36 animate-pulse rounded-lg bg-slate-100" />
          <div className="h-4 w-24 animate-pulse rounded-lg bg-slate-100" />
          <div className="h-20 animate-pulse rounded-2xl bg-slate-100" />
        </div>
      ) : (
        <div className="space-y-3">
          <div className="flex items-start justify-between gap-4">
            <div>
              <div className="text-xl font-semibold">{wordData?.word}</div>
              <button
                type="button"
                onClick={playAudio}
                className="mt-1 rounded-lg px-2 py-1 text-xs text-slate-500 transition hover:bg-slate-100 hover:text-slate-900"
              >
                {wordData?.pronunciation || "点击发音"}
              </button>
            </div>
            <div className="flex gap-2">
              <button
                type="button"
                title="高亮"
                onClick={handleHighlight}
                className="rounded-xl border border-slate-200 px-3 py-2 text-xs font-medium transition hover:border-amber-300 hover:bg-amber-50"
              >
                高亮
              </button>
              <button
                type="button"
                title="收藏"
                onClick={handleCollect}
                className={`rounded-xl px-3 py-2 text-xs font-medium transition ${
                  isCollected
                    ? "bg-amber-100 text-amber-700"
                    : "border border-slate-200 hover:border-sky-300 hover:bg-sky-50"
                }`}
              >
                {isCollected ? "已收藏" : "收藏"}
              </button>
            </div>
          </div>
          <div
            className="rounded-2xl bg-slate-50 px-4 py-3 text-sm leading-7 text-slate-700"
            dangerouslySetInnerHTML={{ __html: wordData?.meaning || "暂无释义" }}
          />
        </div>
      )}
    </div>
  );
}

// entrypoints/content/word_card.vue
<template>
    <div class="bg-white border-1 border-gray-300 rounded-xl min-w-100 min-h-15 p-3 text-black">
        <div v-if="loading_flag" class="items-center justify-center flex h-full py-2">
            <div class="loading loading-dots lodding-sm"></div>
        </div>
        <div v-else class="flex justify-between items-center">
            <div class="flex items-center justify-center">
                <div class="text-xl font-bold">{{ wordData?.word }}</div>
                <div @click="playAudio" class="text-xs text-gray-400 px-2 rounded-sm hover:bg-gray-100 cursor-pointer">
                    {{ wordData?.pronunciation }}
                </div>
            </div>
            <div class="flex items-center justify-center">
                <!-- 高亮按钮 -->
                <div @click="highlightWord" title="高亮"
                    class="rounded mx-1 p-2 text-sm cursor-pointer hover:bg-gray-100 w-10 h-10 flex items-center justify-center select-none">
                    <svg class="w-5 h-5 text-gray-700" viewBox="0 0 24 24" fill="none" stroke="currentColor"
                        stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                        <path d="M9 11l6-6 3 3-6 6H9v-3z"></path>
                        <path d="M13 5l3 3"></path>
                        <path d="M8 17h8"></path>
                        <path d="M6 21h12"></path>
                    </svg>
                </div>
                <!-- 收藏按钮 -->
                <div @click="collect_words" title="收藏"
                    class="rounded p-2 text-sm cursor-pointer w-10 h-10 flex items-center justify-center select-none hover:bg-gray-100">
                    <svg v-if="!is_collected" class="w-5 h-5 text-gray-700" viewBox="0 0 24 24" fill="none"
                        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
                        aria-hidden="true">
                        <path d="M12 17.3l-5.4 3.3 1.5-6.1L3 9.9l6.3-.5L12 3.8l2.7 5.6 6.3.5-5.1 4.6 1.5 6.1z" />
                    </svg>
                    <svg v-else class="w-5 h-5 text-yellow-600" viewBox="0 0 24 24" fill="currentColor"
                        aria-hidden="true">
                        <path d="M12 17.3l-5.4 3.3 1.5-6.1L3 9.9l6.3-.5L12 3.8l2.7 5.6 6.3.5-5.1 4.6 1.5 6.1z" />
                    </svg>
                </div>
            </div>
        </div>

        <div class="py-2 text-sm text-justify" v-html="wordData?.meaning"></div>
    </div>
</template>

<script lang="ts" setup>
import { inject, ref, onMounted } from 'vue';
import { OpenAI } from "openai";
import { collect_word } from '@/libs/word_collector';
import { WordData } from '@/libs/select_word';
import { ai_api_key_storage, ai_api_url_storage, ai_word_model_storage, ai_prompt_storage, collection_words_storage } from "@/libs/local_storage";

let selected_word = inject('wordData') as any;
let eventManager = inject('eventManager') as any;
let cachedWordData = inject('cachedWordData', null) as any;

let loading_flag = ref<boolean>(true);

let wordData = ref<WordData | null>(null);
const is_collected = ref(false);

const default_prompt =
    `
You are an assistant that extracts dictionary-like information.

I will give you a word and its context.  
Return the result strictly as a JSON object with the following TypeScript type:

export type WordData = {
    word: string;
    pronunciation: string;
    meaning: string;
};

Rules:
- Do not include anything outside the JSON.
- "word": exactly the given word.
- "pronunciation": return the phonetic transcription in IPA if possible (e.g., "/wɜːd/"), otherwise leave it as an empty string.
- "meaning": give the chinese meaning of the word in the provided context, concise but clear.just the word meaning, don't include context, this is important.
`

const check_api_config = async () => {
    if (!await ai_api_key_storage.getValue()) {
        wordData.value = {
            word: "Error",
            pronunciation: "",
            meaning: "Please set your OpenAI API key in the settings."
        };
        return false;
    }
    if (!await ai_api_url_storage.getValue()) {
        wordData.value = {
            word: "Error",
            pronunciation: "",
            meaning: "Please set your OpenAI API key in the settings."
        };
        return false;
    }
    if (!await ai_word_model_storage.getValue()) {
        wordData.value = {
            word: "Error",
            pronunciation: "",
            meaning: "Please set your OpenAI API key in the settings."
        };
        return false;
    }
    return true;
};

const ai_trans = async () => {
    if (!await check_api_config()) {
        loading_flag.value = false;
        return;
    }
    if (cachedWordData) {
        wordData.value = {
            word: cachedWordData.word,
            pronunciation: cachedWordData.pronunciation,
            meaning: cachedWordData.meaning
        };
        loading_flag.value = false;
        return;
    }
    const cur_api_url = await ai_api_url_storage.getValue();
    const cur_model = await ai_word_model_storage.getValue();
    const cur_api_key = await ai_api_key_storage.getValue();
    const cur_prompt = await ai_prompt_storage.getValue() || default_prompt;
    const openai = new OpenAI({
        apiKey: cur_api_key!,
        baseURL: cur_api_url!,
        dangerouslyAllowBrowser: true
    });
    const word_info = await selected_word.getValue();
    console.log("Selected word info:", word_info.word, word_info.context);
    const response = await openai.chat.completions.create({
        model: cur_model!,
        messages: [
            { "role": "system", "content": cur_prompt },
            { "role": "user", "content": `Word: ${word_info.word} Context: ${word_info.context}` }
        ],
        response_format: { type: "json_object" }
    });

    const content = response.choices[0].message.content;
    const word_obj = JSON.parse(content!) as WordData;
    wordData.value = word_obj;
    loading_flag.value = false;
}

const highlightWord = async () => {
    if (!wordData.value?.word) return;
    try {
        eventManager.emit('highlight-word', {
            word: wordData.value.word,
            wordData: wordData.value
        });
        eventManager.emit('close-word-card');
    } catch (error) {
        console.error('Error emitting highlight event:', error);
    }
};

const collect_words = async () => {
    if (!wordData.value) return;
    const collected = await f_is_collected();
    if (collected) {
        return;
    }
    await collection_words_storage.setValue([...await collection_words_storage.getValue() || [], wordData.value]);
    const word_info = await selected_word.getValue();
    collect_word(word_info.word, word_info.context);
    is_collected.value = true;
};

const f_is_collected = async () => {
    if (!wordData.value?.word) return true;
    try {
        const storedWords = await collection_words_storage.getValue() || [];
        is_collected.value = storedWords.some(item => item.word === wordData.value?.word);
        if (is_collected.value) {
            return true;
        }
    } catch (error) {
        console.error('Error checking if word is collected:', error);
    }
    return false;
};

const playAudio = () => {
    if (!wordData.value?.word) return;
    const utter = new SpeechSynthesisUtterance(wordData.value.word);
    utter.lang = "en-US";
    speechSynthesis.speak(utter);
};

onMounted(() => {
    ai_trans();
});
</script>
