// entrypoints/content/popup_thumb.vue
<template>
    <div class="flex w-[120px] h-[30px] border-2 justify-around items-center">
        <div @click="eventManager.emit('show-word-card')"
            class="w-[45%] h-[90%] cursor-pointer bg-red-200 justify-center items-center flex active:bg-red-400 select-none">
            单词
        </div>
        <div @click="eventManager.emit('show-ai-trans-card')"
            class="w-[45%] h-[90%] cursor-pointer bg-green-200 flex justify-center items-center active:bg-green-400 select-none">
            翻译
        </div>
    </div>
</template>

<script lang="ts" setup>
import { inject } from 'vue';
const eventManager: any = inject('eventManager');
</script>

// entrypoints/content/views/popup_thumb.tsx
import type { EventManager } from "@/libs/event_manager";

type PopupThumbProps = {
  eventManager: EventManager;
};

function ActionButton({
  label,
  tone,
  onClick,
}: {
  label: string;
  tone: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      className={`flex flex-1 items-center justify-center rounded-xl border px-3 py-2 text-xs font-semibold text-slate-700 transition hover:-translate-y-0.5 ${tone}`}
    >
      {label}
    </button>
  );
}

export default function PopupThumb({ eventManager }: PopupThumbProps) {
  return (
    <div className="flex min-w-[210px] gap-2 rounded-2xl border border-slate-200 bg-white/95 p-2 shadow-[0_12px_30px_rgba(15,23,42,0.12)] backdrop-blur">
      <ActionButton
        label="单词"
        tone="hover:border-sky-300 hover:bg-sky-50"
        onClick={() => eventManager.emit("show-word-card")}
      />
      <ActionButton
        label="翻译"
        tone="hover:border-emerald-300 hover:bg-emerald-50"
        onClick={() => eventManager.emit("show-ai-trans-card")}
      />
      <ActionButton
        label="高亮"
        tone="hover:border-amber-300 hover:bg-amber-50"
        onClick={() => eventManager.emit("highlight-sentence")}
      />
    </div>
  );
}
