// entrypoints/content/views/popup_thumb.vue
<template>
    <div class="bg-white rounded-lg shadow-lg border border-gray-100 p-1 flex gap-1 min-w-[140px]">
        <button @click="eventManager.emit('show-word-card')"
            class="btn btn-sm btn-ghost flex-1 gap-1 hover:bg-blue-50 hover:text-blue-600 transition-all duration-200 border-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="M12 6.042A8.967 8.967 0 0 0 6 3.75c-1.052 0-2.062.18-3 .512v14.25A8.987 8.987 0 0 1 6 18c2.305 0 4.408.867 6 2.292m0-14.25a8.966 8.966 0 0 1 6-2.292c1.052 0 2.062.18 3 .512v14.25A8.987 8.987 0 0 1 18 18a8.967 8.967 0 0 0-6 2.292m0-14.25v14.25" />
            </svg>
            <span class="text-xs font-medium">单词</span>
        </button>
                
        <button @click="eventManager.emit('show-ai-trans-card')"
            class="btn btn-sm btn-ghost flex-1 gap-1 hover:bg-emerald-50 hover:text-emerald-600 transition-all duration-200 border-0">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-4 h-4">
                <path stroke-linecap="round" stroke-linejoin="round" d="m10.5 21 5.25-11.25L21 21m-9-3h7.5M3 5.621a48.474 48.474 0 0 1 6-.371m0 0c1.12 0 2.233.038 3.334.114M9 5.25V3m3.334 2.364C11.176 10.658 7.69 15.08 3 17.502m9.334-12.138c.896.061 1.785.147 2.666.257m-4.589 8.495a18.023 18.023 0 0 1-3.827-5.802" />
            </svg>
            <span class="text-xs font-medium">翻译</span>
        </button>
    </div>
</template>

<script lang="ts" setup>
import { inject } from 'vue';
const eventManager: any = inject('eventManager');
</script>

// entrypoints/content/views/popup_thumb.tsx
import type { ReactNode } from "react";
import type { EventManager } from "@/libs/event_manager";

type PopupThumbProps = {
  eventManager: EventManager;
};

function ActionButton({
  title,
  children,
  tone,
  onClick,
}: {
  title: string;
  children: ReactNode;
  tone: string;
  onClick: () => void;
}) {
  return (
    <button
      type="button"
      onClick={onClick}
      title={title}
      aria-label={title}
      className={`flex h-7 min-w-7 items-center justify-center rounded-full px-2.5 text-xs font-semibold text-slate-700 transition hover:-translate-y-0.5 ${tone}`}
    >
      {children}
    </button>
  );
}

export default function PopupThumb({ eventManager }: PopupThumbProps) {
  return (
    <div className="flex h-8 items-center gap-1 rounded-full border border-slate-200/80 bg-white/90 p-0.5 shadow-[0_6px_16px_rgba(15,23,42,0.12)] backdrop-blur">
      <ActionButton
        title="单词"
        tone="hover:bg-sky-50 hover:text-sky-700"
        onClick={() => eventManager.emit("show-word-card")}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="15"
          height="15"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20" />
          <path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z" />
          <path d="M8 7h8" />
          <path d="M8 11h5" />
        </svg>
      </ActionButton>
      <ActionButton
        title="翻译"
        tone="hover:bg-emerald-50 hover:text-emerald-700"
        onClick={() => eventManager.emit("show-ai-trans-card")}
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          width="15"
          height="15"
          viewBox="0 0 24 24"
          fill="none"
          stroke="currentColor"
          strokeWidth="2.2"
          strokeLinecap="round"
          strokeLinejoin="round"
          aria-hidden="true"
        >
          <path d="m5 8 6 6" />
          <path d="m4 14 6-6 2-3" />
          <path d="M2 5h12" />
          <path d="M7 2h1" />
          <path d="m14 22 5-10 3 10" />
          <path d="M15.5 18h5" />
        </svg>
      </ActionButton>
    </div>
  );
}
